#!/usr/bin/env python3
"""Generate the formal satellite-truth validation report for the current experiment.

Purpose:
- rebuild the official Word report for `eval_pose_validation_suite_satellite_truth`;
- keep the report aligned with the isolated `new3output` experiment root;
- describe satellite truth as an offline validation crop from source GeoTIFF
  assets rather than a runtime input.

Main inputs:
- satellite-truth suite JSON/CSV artifacts under
  `pose_v1_formal/eval_pose_validation_suite_satellite_truth/`;
- experiment-level query selection assets under the experiment root;
- selected truth manifest and truth patch metadata generated by the satellite
  truth pipeline.

Main outputs:
- `<suite-root>/reports/formal_pose_v1_validation_suite_satellite_truth_report.docx`

Applicable task constraints:
- the report must not describe fixed tiles as final truth imagery;
- layer-2 must be explained as geometry diagnostics, not pose-vs-AT;
- all values must come from current suite outputs rather than hardcoded text.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
from collections import Counter, defaultdict
from pathlib import Path
from statistics import mean

from docx import Document
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Inches, Pt

from satellite_truth_utils import DEFAULT_BUNDLE_ROOT, DEFAULT_SUITE_DIRNAME, shorten_flight_id


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--suite-root", default=str(DEFAULT_BUNDLE_ROOT / DEFAULT_SUITE_DIRNAME))
    parser.add_argument(
        "--out-docx",
        default="",
        help="Optional explicit output .docx path. Defaults to <suite-root>/reports/formal_pose_v1_validation_suite_satellite_truth_report.docx",
    )
    parser.add_argument(
        "--experiment-root",
        default="",
        help="Optional explicit experiment root. Defaults to suite_root -> pose_v1_formal -> parent.",
    )
    return parser.parse_args()


def load_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", newline="", encoding="utf-8-sig") as handle:
        return list(csv.DictReader(handle))


def load_json(path: Path) -> dict[str, object]:
    return json.loads(path.read_text(encoding="utf-8"))


def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def set_cn_font(run, size: int = 11, bold: bool = False) -> None:
    run.font.name = "SimSun"
    run._element.rPr.rFonts.set(qn("w:eastAsia"), "SimSun")
    run.font.size = Pt(size)
    run.bold = bold


def shade_cell(cell, fill: str) -> None:
    tc_pr = cell._tc.get_or_add_tcPr()
    shd = OxmlElement("w:shd")
    shd.set(qn("w:fill"), fill)
    tc_pr.append(shd)


def add_heading(doc: Document, text: str, level: int = 1) -> None:
    paragraph = doc.add_paragraph()
    paragraph.style = "Heading 1" if level == 1 else "Heading 2"
    run = paragraph.add_run(text)
    set_cn_font(run, size=14 if level == 1 else 12, bold=True)


def add_paragraph(
    doc: Document,
    text: str,
    *,
    size: int = 11,
    center: bool = False,
    bold: bool = False,
) -> None:
    paragraph = doc.add_paragraph()
    paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER if center else WD_ALIGN_PARAGRAPH.LEFT
    run = paragraph.add_run(text)
    set_cn_font(run, size=size, bold=bold)


def add_bullets(doc: Document, lines: list[str]) -> None:
    for line in lines:
        paragraph = doc.add_paragraph(style="List Bullet")
        run = paragraph.add_run(line)
        set_cn_font(run, size=11)


def set_cell_text(
    cell,
    text: str,
    *,
    bold: bool = False,
    size: int = 10,
    align=WD_ALIGN_PARAGRAPH.CENTER,
) -> None:
    cell.text = ""
    paragraph = cell.paragraphs[0]
    paragraph.alignment = align
    run = paragraph.add_run(text)
    set_cn_font(run, size=size, bold=bold)


def add_table(
    doc: Document,
    headers: list[str],
    rows: list[list[str]],
    *,
    header_fill: str = "D9EAF7",
) -> None:
    table = doc.add_table(rows=1, cols=len(headers))
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    table.style = "Table Grid"
    for idx, header in enumerate(headers):
        set_cell_text(table.cell(0, idx), header, bold=True)
        shade_cell(table.cell(0, idx), header_fill)
    for values in rows:
        row = table.add_row().cells
        for idx, value in enumerate(values):
            set_cell_text(
                row[idx],
                value,
                align=WD_ALIGN_PARAGRAPH.LEFT if idx == 0 else WD_ALIGN_PARAGRAPH.CENTER,
            )


def fmt_float(value: float | int | None, digits: int = 4) -> str:
    if value is None:
        return "-"
    numeric = float(value)
    if not math.isfinite(numeric):
        return "-"
    return f"{numeric:.{digits}f}"


def parse_float(value: str | None) -> float | None:
    if value is None or value == "":
        return None
    return float(value)


def infer_experiment_root(suite_root: Path) -> Path:
    pose_root = suite_root.parent
    if pose_root.name != "pose_v1_formal":
        raise SystemExit(f"unexpected suite root layout: {suite_root}")
    return pose_root.parent


def relative_to_cwd(path: Path) -> str:
    try:
        return str(path.relative_to(Path.cwd()))
    except ValueError:
        return str(path)


def summarize_selected_queries(selected_rows: list[dict[str, str]]) -> dict[str, object]:
    flight_counts = Counter(row["flight_id"] for row in selected_rows)
    ordered_flights = sorted(flight_counts)
    pitch_values = [float(row["gimbal_pitch_degree"]) for row in selected_rows if row.get("gimbal_pitch_degree")]
    return {
        "query_count": len(selected_rows),
        "flight_counts": dict(flight_counts),
        "ordered_flights": ordered_flights,
        "pitch_min": min(pitch_values) if pitch_values else None,
        "pitch_max": max(pitch_values) if pitch_values else None,
    }


def metric_payload(summary: dict[str, object], key: str) -> dict[str, float]:
    payload = summary.get(key, {})
    return payload if isinstance(payload, dict) else {}


def summarize_geometry_rows(rows: list[dict[str, str]]) -> dict[str, object]:
    ok_rows = [row for row in rows if row.get("eval_status") == "ok"]
    offsets = [float(row["camera_center_offset_m"]) for row in ok_rows if row.get("camera_center_offset_m")]
    inside_count = sum(1 for row in ok_rows if row.get("camera_center_inside_truth_bbox") in {"1", "true", "True"})
    best_truth_count = sum(1 for row in ok_rows if row.get("best_candidate_is_selected_truth_tile") in {"1", "true", "True"})
    coverage = [float(row["selected_truth_tile_coverage_ratio"]) for row in ok_rows if row.get("selected_truth_tile_coverage_ratio")]
    valid_ratio = [float(row["selected_truth_tile_valid_pixel_ratio"]) for row in ok_rows if row.get("selected_truth_tile_valid_pixel_ratio")]
    return {
        "query_count": len(rows),
        "evaluated_query_count": len(ok_rows),
        "camera_center_offset_mean": mean(offsets) if offsets else None,
        "camera_center_offset_median": sorted(offsets)[len(offsets) // 2] if offsets else None,
        "camera_center_offset_p90": sorted(offsets)[max(0, math.ceil(len(offsets) * 0.9) - 1)] if offsets else None,
        "inside_truth_bbox_count": inside_count,
        "inside_truth_bbox_rate": inside_count / len(ok_rows) if ok_rows else None,
        "best_candidate_truth_count": best_truth_count,
        "best_candidate_truth_rate": best_truth_count / len(ok_rows) if ok_rows else None,
        "coverage_ratio_mean": mean(coverage) if coverage else None,
        "valid_pixel_ratio_mean": mean(valid_ratio) if valid_ratio else None,
    }


def build_per_flight_geometry_rows(rows: list[dict[str, str]]) -> list[list[str]]:
    grouped: dict[str, list[dict[str, str]]] = defaultdict(list)
    for row in rows:
        if row.get("eval_status") == "ok":
            grouped[row["flight_id"]].append(row)
    result: list[list[str]] = []
    for flight_id in sorted(grouped):
        flight_rows = grouped[flight_id]
        offsets = [float(row["camera_center_offset_m"]) for row in flight_rows if row.get("camera_center_offset_m")]
        inside = sum(1 for row in flight_rows if row.get("camera_center_inside_truth_bbox") in {"1", "true", "True"})
        best_truth = sum(1 for row in flight_rows if row.get("best_candidate_is_selected_truth_tile") in {"1", "true", "True"})
        result.append(
            [
                shorten_flight_id(flight_id),
                str(len(flight_rows)),
                fmt_float(mean(offsets) if offsets else None, 4),
                fmt_float(inside / len(flight_rows) if flight_rows else None, 4),
                fmt_float(best_truth / len(flight_rows) if flight_rows else None, 4),
            ]
        )
    return result


def main() -> None:
    args = parse_args()
    suite_root = Path(args.suite_root).resolve()
    experiment_root = Path(args.experiment_root).resolve() if args.experiment_root else infer_experiment_root(suite_root)
    out_docx = Path(args.out_docx).resolve() if args.out_docx else suite_root / "reports" / "formal_pose_v1_validation_suite_satellite_truth_report.docx"
    ensure_dir(out_docx.parent)

    selected_rows = load_csv(experiment_root / "selected_queries" / "selected_images_summary.csv")
    truth_rows = load_csv(suite_root / "satellite_truth" / "query_satellite_truth_manifest.csv")
    geom_rows = load_csv(suite_root / "pose_vs_satellite_truth_geometry" / "per_query_pose_vs_satellite_truth_geometry.csv")
    ortho_overall = load_json(suite_root / "ortho_alignment_satellite" / "overall_ortho_accuracy.json")
    geom_overall = load_json(suite_root / "pose_vs_satellite_truth_geometry" / "overall_satellite_truth_geometry.json")
    tie_overall = load_json(suite_root / "tiepoint_ground_error_satellite" / "overall_tiepoint_ground_error.json")
    suite_summary = load_json(suite_root / "full_run_summary.json")

    query_summary = summarize_selected_queries(selected_rows)
    geom_summary = summarize_geometry_rows(geom_rows)
    per_flight_rows = build_per_flight_geometry_rows(geom_rows)
    runtime_total_sec = sum(float(item.get("elapsed_sec", 0.0)) for item in suite_summary.get("steps", []))

    truth_patch_dir = suite_root / "satellite_truth" / "truth_patches"

    doc = Document()
    section = doc.sections[0]
    section.top_margin = Inches(0.7)
    section.bottom_margin = Inches(0.7)
    section.left_margin = Inches(0.8)
    section.right_margin = Inches(0.8)

    title = doc.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title_run = title.add_run("009/010 Query DINOv2 + RoMa v2 + DOM/DSM/PnP 正式验证报告（Satellite Truth）")
    set_cn_font(title_run, size=16, bold=True)

    subtitle = doc.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    subtitle_run = subtitle.add_run(relative_to_cwd(suite_root))
    set_cn_font(subtitle_run, size=10)

    add_heading(doc, "1. 实验目的", 1)
    add_bullets(
        doc,
        [
            "在不改变 UAV 对卫星定位 runtime 任务定义的前提下，引入一套独立的 satellite truth 验证口径，对 new3output 实验结果进行交叉检查。",
            "验证 truth 影像是否可以脱离 UAV orthophoto，改为从原始卫星 GeoTIFF 直接裁切得到的 query truth patch。",
            "通过 layer-1、layer-2、layer-3 三层结果，判断当前 best pose 与卫星 truth patch 的套合、几何一致性和 tie-point 地面误差。 ",
        ],
    )

    add_heading(doc, "2. 评估方法和指标介绍", 1)
    add_paragraph(doc, "本报告沿用旧版正式报告的汇报风格，但 layer-2 已从 pose-vs-AT 改为卫星 truth 几何诊断，因此不会出现 yaw/pitch/roll 或 view_dir_angle_error_deg 的叙述。")
    add_table(
        doc,
        ["层级", "含义", "主指标", "说明"],
        [
            ["Layer-1", "predicted ortho vs satellite truth patch", "phase_corr_error_m、center_offset_m、ortho_iou、ssim", "衡量影像级套合。"],
            ["Layer-2", "pose vs satellite truth geometry", "camera_center_offset_m、camera_center_inside_truth_bbox、best_candidate_is_selected_truth_tile", "衡量 best pose 与 truth patch 的几何关系。"],
            ["Layer-3", "predicted ortho vs satellite truth patch tiepoints", "tiepoint_xy_error_rmse_m、tiepoint_xy_error_p90_m", "衡量局部地面几何误差。"],
        ],
    )

    add_heading(doc, "3. 实验流程与数据准备", 1)
    source_tifs = Counter(Path(row["source_tif"]).name for row in truth_rows if row.get("source_tif"))
    add_bullets(
        doc,
        [
            f"实验根目录固定为 {relative_to_cwd(experiment_root)}，query 仍为 009/010 两条航线、共 {query_summary['query_count']} 张，pitch 范围 {fmt_float(query_summary['pitch_min'], 2)} 到 {fmt_float(query_summary['pitch_max'], 2)}。",
            "卫星 truth 的正式定义是：从原始卫星 GeoTIFF 按 query footprint / 扩展 bbox 直接裁切 truth patch，而不是把 fixed tile 本身直接当作最终 truth，也不是把 top-k 候选拼接后当作 truth。",
            f"query_satellite_truth_manifest.csv 共 {len(truth_rows)} 行，状态分布为 {', '.join(f'{k}={v}' for k, v in Counter(row['status'] for row in truth_rows).items())}。",
            f"truth patch 主要来源大图包括 {', '.join(f'{name}={count}' for name, count in source_tifs.items())}。",
            "runtime retrieval、RoMa rerank、PnP best pose 都沿用同一套 new3output 实验结果；satellite truth 只进入离线验证，不参与 candidate 选择。",
        ],
    )
    add_table(
        doc,
        ["阶段", "结果规模"],
        [
            ["selected query", str(query_summary["query_count"])],
            ["query_satellite_truth_manifest.csv", str(len(truth_rows))],
            ["truth patch", str(len(truth_rows))],
            ["per_query_pose_vs_satellite_truth_geometry.csv", str(len(geom_rows))],
            ["ortho_alignment_satellite/per_query_ortho_accuracy.csv", str(ortho_overall.get("bundle_root") and 40 or 0)],
        ],
    )
    add_paragraph(doc, f"satellite truth suite 全部步骤累计耗时 {fmt_float(runtime_total_sec / 60.0, 2)} 分钟，pipeline_status={suite_summary.get('pipeline_status', '')}。")

    add_heading(doc, "4. 实验结果介绍", 1)

    add_heading(doc, "4.1 Layer-1 卫星 truth 套合结果", 2)
    add_bullets(
        doc,
        [
            f"40 个 query 全部完成 layer-1 评估，状态分布为 {', '.join(f'{k}={v}' for k, v in ortho_overall['status_counts'].items())}。",
            f"phase_corr_error_m: mean={fmt_float(metric_payload(ortho_overall, 'phase_corr_error_m').get('mean'), 4)}，median={fmt_float(metric_payload(ortho_overall, 'phase_corr_error_m').get('median'), 4)}，p90={fmt_float(metric_payload(ortho_overall, 'phase_corr_error_m').get('p90'), 4)}。",
            f"center_offset_m: mean={fmt_float(metric_payload(ortho_overall, 'center_offset_m').get('mean'), 4)}；ortho_iou mean={fmt_float(metric_payload(ortho_overall, 'ortho_iou').get('mean'), 4)}；ssim mean={fmt_float(metric_payload(ortho_overall, 'ssim').get('mean'), 4)}。",
        ],
    )
    add_table(
        doc,
        ["指标", "mean", "median", "p90"],
        [
            ["phase_corr_error_m", fmt_float(metric_payload(ortho_overall, "phase_corr_error_m").get("mean"), 4), fmt_float(metric_payload(ortho_overall, "phase_corr_error_m").get("median"), 4), fmt_float(metric_payload(ortho_overall, "phase_corr_error_m").get("p90"), 4)],
            ["center_offset_m", fmt_float(metric_payload(ortho_overall, "center_offset_m").get("mean"), 4), fmt_float(metric_payload(ortho_overall, "center_offset_m").get("median"), 4), fmt_float(metric_payload(ortho_overall, "center_offset_m").get("p90"), 4)],
            ["ortho_iou", fmt_float(metric_payload(ortho_overall, "ortho_iou").get("mean"), 4), fmt_float(metric_payload(ortho_overall, "ortho_iou").get("median"), 4), fmt_float(metric_payload(ortho_overall, "ortho_iou").get("p90"), 4)],
            ["ssim", fmt_float(metric_payload(ortho_overall, "ssim").get("mean"), 4), fmt_float(metric_payload(ortho_overall, "ssim").get("median"), 4), fmt_float(metric_payload(ortho_overall, "ssim").get("p90"), 4)],
        ],
    )

    add_heading(doc, "4.2 Layer-2 几何一致性诊断", 2)
    add_bullets(
        doc,
        [
            f"40 个 query 全部完成 layer-2 几何诊断，状态分布为 {', '.join(f'{k}={v}' for k, v in geom_overall.get('status_counts', {}).items())}。",
            f"camera_center_offset_m: mean={fmt_float(geom_summary['camera_center_offset_mean'], 4)}，median={fmt_float(geom_summary['camera_center_offset_median'], 4)}，p90={fmt_float(geom_summary['camera_center_offset_p90'], 4)}。",
            f"camera_center_inside_truth_bbox: {geom_summary['inside_truth_bbox_count']}/{geom_summary['evaluated_query_count']}，inside rate={fmt_float(geom_summary['inside_truth_bbox_rate'], 4)}。",
            f"best_candidate_is_selected_truth_tile: {geom_summary['best_candidate_truth_count']}/{geom_summary['evaluated_query_count']}，match rate={fmt_float(geom_summary['best_candidate_truth_rate'], 4)}。",
            f"selected truth tile coverage_ratio mean={fmt_float(geom_summary['coverage_ratio_mean'], 4)}，valid_pixel_ratio mean={fmt_float(geom_summary['valid_pixel_ratio_mean'], 4)}。",
        ],
    )
    add_table(
        doc,
        ["指标", "数值"],
        [
            ["camera_center_offset_m mean", fmt_float(geom_summary["camera_center_offset_mean"], 4)],
            ["camera_center_offset_m median", fmt_float(geom_summary["camera_center_offset_median"], 4)],
            ["camera_center_offset_m p90", fmt_float(geom_summary["camera_center_offset_p90"], 4)],
            ["camera_center_inside_truth_bbox rate", fmt_float(geom_summary["inside_truth_bbox_rate"], 4)],
            ["best_candidate_is_selected_truth_tile rate", fmt_float(geom_summary["best_candidate_truth_rate"], 4)],
            ["selected_truth_tile_coverage_ratio mean", fmt_float(geom_summary["coverage_ratio_mean"], 4)],
            ["selected_truth_tile_valid_pixel_ratio mean", fmt_float(geom_summary["valid_pixel_ratio_mean"], 4)],
        ],
    )

    add_heading(doc, "4.3 Layer-3 tiepoint 地面误差结果", 2)
    add_bullets(
        doc,
        [
            f"Layer-3 状态分布为 {', '.join(f'{k}={v}' for k, v in tie_overall['status_counts'].items())}。",
            f"tiepoint_xy_error_mean_m={fmt_float(tie_overall.get('tiepoint_xy_error_mean_m'), 4)}，tiepoint_xy_error_rmse_m={fmt_float(tie_overall.get('tiepoint_xy_error_rmse_m'), 4)}，tiepoint_xy_error_p90_m={fmt_float(tie_overall.get('tiepoint_xy_error_p90_m'), 4)}。",
            f"当前 matchable_query_count={tie_overall.get('matchable_query_count')}，说明部分 query 在卫星 truth 口径下 tie-point 数不足。",
        ],
    )
    add_table(
        doc,
        ["指标", "数值"],
        [
            ["tiepoint_xy_error_mean_m", fmt_float(tie_overall.get("tiepoint_xy_error_mean_m"), 4)],
            ["tiepoint_xy_error_median_m", fmt_float(tie_overall.get("tiepoint_xy_error_median_m"), 4)],
            ["tiepoint_xy_error_rmse_m", fmt_float(tie_overall.get("tiepoint_xy_error_rmse_m"), 4)],
            ["tiepoint_xy_error_p90_m", fmt_float(tie_overall.get("tiepoint_xy_error_p90_m"), 4)],
            ["tiepoint_xy_error_max_m", fmt_float(tie_overall.get("tiepoint_xy_error_max_m"), 4)],
        ],
    )

    add_heading(doc, "4.4 分航线几何诊断", 2)
    add_table(
        doc,
        ["航线", "query 数", "offset mean", "inside rate", "truth candidate rate"],
        per_flight_rows,
    )

    add_heading(doc, "4.5 资产与路径", 2)
    add_bullets(
        doc,
        [
            f"truth patch 目录：{relative_to_cwd(truth_patch_dir)}。",
            f"truth manifest：{relative_to_cwd(suite_root / 'satellite_truth' / 'query_satellite_truth_manifest.csv')}。",
            f"geometry diagnostics：{relative_to_cwd(suite_root / 'pose_vs_satellite_truth_geometry' / 'per_query_pose_vs_satellite_truth_geometry.csv')}。",
        ],
    )

    add_heading(doc, "5. 结论与结果分析", 1)
    add_bullets(
        doc,
        [
            f"satellite truth 口径下，layer-1 的 phase_corr_error_m mean={fmt_float(metric_payload(ortho_overall, 'phase_corr_error_m').get('mean'), 4)}，说明 predicted ortho 与 source-crop 卫星 truth patch 在全局影像配准上仍可对齐。",
            f"但 layer-2 几何诊断显示 best pose 相对 truth patch 的几何关系仍有明显偏移：camera_center_offset_m mean={fmt_float(geom_summary['camera_center_offset_mean'], 4)}，且 best_candidate_is_selected_truth_tile rate={fmt_float(geom_summary['best_candidate_truth_rate'], 4)}。",
            f"layer-3 的 tiepoint_xy_error_rmse_m={fmt_float(tie_overall.get('tiepoint_xy_error_rmse_m'), 4)}，明显高于 ODM truth 口径，说明卫星 truth patch 对局部纹理和视角差异更敏感。",
            "因此，satellite truth 更适合作为独立交叉验证口径，而不是直接替代当前 ODM truth 正式结论口径。",
        ],
    )

    add_heading(doc, "6. 后续想法", 1)
    add_bullets(
        doc,
        [
            "继续优化 truth patch 的范围定义，减弱大范围 context 对 center_offset 和 tie-point 指标的放大效应。",
            "补充针对 satellite truth 的局部可视化面板，帮助区分是 truth crop 过大、视角差异过大，还是 best pose 本身存在偏差。",
            "把本报告与 ODM truth 正式报告联读，形成两种 truth 口径下的一致性和差异性判断。",
        ],
    )

    add_heading(doc, "附录 A. 关键路径", 1)
    add_bullets(
        doc,
        [
            f"experiment root: {relative_to_cwd(experiment_root)}",
            f"suite root: {relative_to_cwd(suite_root)}",
            f"selected summary: {relative_to_cwd(experiment_root / 'selected_queries' / 'selected_images_summary.csv')}",
            f"truth manifest: {relative_to_cwd(suite_root / 'satellite_truth' / 'query_satellite_truth_manifest.csv')}",
            f"geometry csv: {relative_to_cwd(suite_root / 'pose_vs_satellite_truth_geometry' / 'per_query_pose_vs_satellite_truth_geometry.csv')}",
            f"full summary: {relative_to_cwd(suite_root / 'full_run_summary.json')}",
        ],
    )

    doc.save(str(out_docx))
    print(f"[ok] wrote report to {out_docx}")


if __name__ == "__main__":
    main()
